main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
url: ${project.url}
version: ${project.version}
authors:
  - Steffion
description: An easy to set up, Hide and seek plugin. Hide as blocks from the killer seekers.
softdepend: [LibsDisguises, ProtocolLib, Multiverse-Core, My Worlds]
load: POSTWORLD
commands:
  BlockHunt:
    usage: /<command>
    description: N/A
    aliases:
        - bh
        - prophunt
        - ph
        - hideandseek
        - has
        - hs
        - seekandfind
        - saf
        - sf
