name: BlockHunt
main: nl.Steffion.BlockHunt.BlockHunt
version: 0.2.0_BETA_B5
authors:
  - 'Steffion'
description: An easy to set up, Hide and seek plugin. Hide as blocks from the killer seekers.
softdepend: [LibsDisguises, ProtocolLib, Multiverse-Core, My Worlds, Vault]
load: POSTWORLD
commands:
  BlockHunt:
    usage: /<command>
    description: N/A
    aliases:
        - bh
        - blockhunt
        - blockh
        - bhunt
