name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
authors:
  - 'Steffion'
description: An easy to set up, Hide and seek plugin. Hide as blocks from the killer seekers.
softdepend: [LibsDisguises, ProtocolLib, Multiverse-Core, My Worlds, Vault]
load: POSTWORLD
commands:
  BlockHunt:
    usage: /<command>
    description: N/A
    aliases:
        - bh
        - blockhunt
        - blockh
        - bhunt
